// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcHERL0OxG-iUdCfU4J5V5KQOOPZIk7P4',              // De firebaseConfig.apiKey
    appId: '1:853064190936:android:7afc6fb4882acd76de00ad',                // De firebaseConfig.appId
    messagingSenderId: '853064190936', // De firebaseConfig.messagingSenderId
    projectId: 'reminder-aa13d',                 // Este ya está correcto
    storageBucket: 'reminder-aa13d.firebasestorage.app', // Este ya está correcto
  );
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional

  
}
